"""add_time_controls_to_game

Revision ID: 3605cc4e4cfc
Revises: af5330e8cef6
Create Date: 2026-08-05

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3605cc4e4cfc'
down_revision: Union[str, Sequence[str], None] = 'af5330e8cef6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('base_time_ms', sa.Integer(), server_default='180000', nullable=False))
    op.add_column('games', sa.Column('increment_ms', sa.Integer(), server_default='0', nullable=False))
    op.add_column('games', sa.Column('is_rated', sa.Boolean(), server_default='true', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'is_rated')
    op.drop_column('games', 'increment_ms')
    op.drop_column('games', 'base_time_ms')
    # ### end Alembic commands ###